fixed error

diff --git a/.github/01-building-blocks.yaml b/.github/01-building-blocks.yaml
--- a/.github/01-building-blocks.yaml
+++ b/.github/01-building-blocks.yaml
@@ -13,7 +13,7 @@ jobs:
     steps:
     - name: Failed steps
       run: |
-      echo " I WILL FAIL"
-      exit 1
+        echo " I WILL FAIL"
+        exit 1
     - name: Say Goodbye
       run: echo "Goodbye!!"  
